apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-api-jwt-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak-sebastian-mammoliti-dev.apps.rm2.thpm.p1.openshiftapps.com/realms/spring-api
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/spring-api/protocol/openid-connect/certs
