apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  labels:
    app: keycloak
type: Opaque
stringData:
 KC_BOOTSTRAP_ADMIN_USERNAME: admin
 KC_BOOTSTRAP_ADMIN_PASSWORD: Password123!