apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    app: keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    app: keycloak
data:
  spring-api-realm.json: |
    {
      "realm": "spring-api",
      "enabled": true,
      "displayName": "Spring API",
      "clients": [
        {
          "clientId": "spring-api",
          "name": "Spring API Client",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "clientAuthenticatorType": "client-secret",
          "secret": "ChangeMe123!",
          "serviceAccountsEnabled": true,
          "standardFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "authorizationServicesEnabled": false,
          "fullScopeAllowed": true
        }
      ]
    }